server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback - rutele Angular sa nu dea 404
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache pentru assets statice
    location ~* \.(js|css|woff|woff2|svg|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
