@HostAddress = http://localhost:5233
###
POST {{HostAddress}}/api/posts
Content-Type: application/json

{
  "Descriere": "Prima mea postare din VS Code!",
  "ImageUrl": "/images/image1.jpg",
  "Hashtag": "#programare"
}
###
GET {{HostAddress}}/api/posts